### ISSUE TITLE
MXP-002 - Implement static linkage of ffmpeg libs

### ISSUE THREAD

**Issue by mwgoldsmith** [mwgoldsmith/MediaExplorerPro#7]
- libavformat
  - libavcodec
  - libavutil
  - libswresample
    - libsoxr
  - libgme
  - libmodplug
  - libssh
    - libz
    - libgcrypt
  - librtmp
    - libgnutls
  - libgnutls
    - libz
    - libiconv
    - libnettle
    - libhogweed
      - libgmp
      - libnettle
  - libbluray

**Text (rendering, rasterization, encoding, parsing, ...)**
- [x] freetype2 - performs font rasterization
- [x] fontconfig - performs font selection based on a pattern of desired font characteristics
- [ ] fribidi - implementation of the Unicode Bidirectional Algorithm to support Hebrew and Arabic
- [x] harfbuzz - implementation of an OpenType layout engine; performs text shaping
- [x] enca - performs character encoding detection of text
- [x] libiconv - performs character encoding conversions of text
- [x] libxml2 - XML parser and toolkit

**Media Disk Access:**
- [ ] libaacs - implementation of Advanced Access Content System specification for Blu-ray playback.
- [ ] libbdplus - implementation of the BD+ System Specifications for Blu-ray playback.
- [ ] libbluray - provides playback of Blu-ray disks
- [ ] libdvdcss - provides DVD decryption allowing access it as a block like device
- [ ] libdvdread - provides a foundation for reading DVD video disks
- [ ] libdvdnav - provides DVD navigation features such as menus, multiangle playback, etc.
- [ ] libcdio - a library for CD-ROM and CD image access
- [ ] libcdio-paranoia - provides CDDA audio access

**Containers:**
- [ ] ogg -

**Video:**
- [ ] libvpx - WebM VP8/VP9 Codec SDK
- [x] xvid - high quality MPEG-4 codec
- [ ] libtheora - codec derived from the formerly proprietary VP3 codec
- [ ] x264 - H.264/MPEG-4 AVC format codec for video streams
- [ ] x265 - H.265/High Efficiency Video Coding (HEVC) format codec for video streams

**Audio:**
- [ ] game-music-emu - collection of video game music file emulators
- [ ] lame - high quality MPEG Audio Layer III (MP3) encoder
- [ ] modplug - a ModPlug audio rendering engine
- [ ] opus - codec for interactive speech and audio transmission over the Internet
- [ ] vorbis - codec roughly comparable to others such as MP3, VQF, AAC, etc.
- [ ] speex - codec designed to compress voice at bitrates in the 2-45 kbps range
- [ ] libilbc - speech codec suitable for voice communication over IP
- [ ] fdk-aac - Fraunhofer FDK AAC codec

**Other:**
- [ ] libass - subtitle renderer
- [x] soxr - performs one-dimensional sample-rate conversion

**Network:**
- [ ] libssh - implementation of the SSHv2 and SSHv1 protocol for client and server uses
- [ ] openssl - a toolkit implementing SSL v2/v3 and TLS v1 protocols
- [ ] rtmpdump - 
- [ ] gnutls -

**Compression:**
- [x] liblzma 
- [x] bzip2
- [x] zlib

**Specialized Functionality:**
- [x] gmp - a library for arbitrary precision arithmetic
- [ ] libgcrypt - general purpose cryptographic library from GnuPG
- [ ] libgpg-error - library with error codes and descriptions shared by most GnuPG related software
- [ ] libnettle - symmetric crypto algorithms
- [ ] libhogweed - part of nettle containing public key algorithms that depend on GMP
